FishingProject/Models/Organization.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace FishingProject.Models
{
    public class Organization
    {
        [Key]
        public int OrganizationId { get; set; }
        [Display(Name = "First Name")]
        public string FirstName { get; set; }
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [ForeignKey("ApplicationUser")]
        public string ApplicationId { get; set; }
        public ApplicationUser ApplicationUser { get; set; }
    }
}

FishingProject/Models/Tournament.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace FishingProject.Models
{
    public class Tournament
    {
        [Key]
        public int TournamentId { get; set; }
        [Display(Name = "Tournament Name")]
        public string TournamentName { get; set; }
        [Display(Name = "Tournament Date")]
        [DataType(DataType.Date)]
        public DateTime? TournamentDate { get; set; }

        [ForeignKey("Lake")]
        public int LakeId { get; set; }
        public Lake Lake { get; set; }

        [ForeignKey("Organization")]
        public int OrganizationId { get; set; }
        public Organization Organization { get; set; }
    }
}

FishingProject/Controllers/OrganizationsController.cs
using FishingProject.Models;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
namespace FishingProject.Controllers
{
    public class OrganizationsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Organizations
        public ActionResult Index()
        {
            var organizationId = User.Identity.GetUserId();
            var organization = db.Organizations.Where(o => o.ApplicationId == organizationId).ToList();
            return View(organization);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "OrganizationId,FirstName,LastName")] Organization organization)
        {
            if (ModelState.IsValid)
            {
                organization.ApplicationId = User.Identity.GetUserId();
                db.Organizations.Add(organization);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(organization);
        }

        // GET: Tournaments/Shows a List of tournaments from the most current date down
        public ActionResult TournamentIndex()
        {
            var tournaments = db.Tournaments.ToList().OrderByDescending(t => t.TournamentDate);
            return View(tournaments);
        }

        //Lets the organization create new tournaments that includes the Lake information
        public ActionResult CreateTournament()
        {
            Tournament tournament = new Tournament();
            ViewBag.Lakes = new SelectList(db.Lakes.ToList(), "LakeId", "Name");
            return View(tournament); 
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateTournament([Bind(Include = "TournamentId,TournamentName,TournamentDate,LakeId,OrganizationId")] Tournament tournament)
        {
            if (ModelState.IsValid)
            {
                var currentUserId = User.Identity.GetUserId();
                Organization organization = db.Organizations.Where(o => o.ApplicationId == currentUserId).Single();
                tournament.OrganizationId = organization.OrganizationId;
                db.Tournaments.Add(tournament);
                db.SaveChanges();
                return RedirectToAction("TournamentIndex");
            }
            return View(tournament);
        }

        //Get: Details of Tournament
        public ActionResult TournamentDetails(int? id)
        {
            var tournament = db.Tournaments.Include(t => t.Lake.Address).FirstOrDefault(t => t.TournamentId == id);
            return View(tournament);
        }

        // GET: Tournament/Edit/5
        public ActionResult EditTournamentTeam(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TournamentTeam tournamentTeam = db.TournamentTeams.Find(id);
            if (tournamentTeam == null)
            {
                return HttpNotFound();
            }
            return View(tournamentTeam);
        }

        // POST: Tournament/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditTournamentTeam(TournamentTeam tournamentTeam)
        {
            var tournamentTeamId = db.TournamentTeams.Include(t => t.Team).Include(t => t.Tournament).Where(t => t.TournamentTeamId == tournamentTeam.TournamentTeamId).Single();
            tournamentTeamId.TotalWeight = tournamentTeam.TotalWeight;
            tournamentTeamId.BigBass = tournamentTeam.BigBass;
            tournamentTeamId.NumberOfFishes = tournamentTeam.NumberOfFishes;
            db.Entry(tournamentTeamId).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("TournamentTable", new { id = tournamentTeamId.TournamentId });
        }

        //GET: List of tournament teams of certain tournament by the highest weight down 
        public ActionResult TournamentTable(int id)
        {
            var tournamentId = db.TournamentTeams.OrderByDescending(t => t.TotalWeight).Include(t => t.Team).Where(t => t.TournamentId == id);
            return View(tournamentId);
        }
        
        // GET: Teams/Delete
        public ActionResult DeleteTeam(int? id)
     {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TournamentTeam tournamentTeam = db.TournamentTeams.Include(t => t.Team).Include(t => t.Tournament).Where(t => t.TournamentTeamId == id).FirstOrDefault();
            if (tournamentTeam == null)
            {
                return HttpNotFound();
            }
            return View(tournamentTeam);
        }

        // POST: Teams/Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteTeam(TournamentTeam tournamentTeam)
        {
            var tournamentTeamId = db.TournamentTeams.Find(tournamentTeam.TournamentTeamId);
            db.TournamentTeams.Remove(tournamentTeamId);
            db.SaveChanges();
            return RedirectToAction("TournamentTable", new { id = tournamentTeamId.TournamentId });
        }

        public string ConvertAddressToGoogleFormat(Address address)
        {
            string googleFormatAddress = address.StreetAddress + "," + address.City + "," + address.State + "," + address.ZipCode + "," + address.Country;
            return googleFormatAddress;
        }

        public GeoCode GeoLocate(string address)
        {
            var key = Keys.GoogleGeoCodeAPIKey;
            var requestUrl = $"https://maps.googleapis.com/maps/api/geocode/json?address={address}&key={key}";
            var result = new WebClient().DownloadString(requestUrl);
            GeoCode geocode = JsonConvert.DeserializeObject<GeoCode>(result);
            return geocode;
        }

        //Create Lake so that when you create a tournament it can be selected in the drop down box
        public ActionResult CreateLake()
        {
            Lake lake = new Lake();
            return View(lake);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateLake([Bind(Include = "LakeId,Name,Address")] Lake lake)
        {
            if (ModelState.IsValid)
            {
                Address address = new Address();
                address = lake.Address;
                address.Country = "USA";
                string addressToConvert = ConvertAddressToGoogleFormat(address);
                var geoLocate = GeoLocate(addressToConvert);
                address.Longitude = geoLocate.results[0].geometry.location.lng;
                address.Latitude = geoLocate.results[0].geometry.location.lat;
                db.Lakes.Add(lake);
                db.SaveChanges();
                return RedirectToAction("TournamentIndex");
            }
            return View(lake);
        }

        //Creating a product/merchandise to put for sale in ecommerce store
        public ActionResult CreateProduct()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateProduct([Bind(Include = "Name,Price")] Product product, HttpPostedFileBase upload)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (upload != null && upload.ContentLength > 0)
                    {
                        var photo = new File
                        {
                            FileName = System.IO.Path.GetFileName(upload.FileName),
                            FileType = FileType.Picture,
                            ContentType = upload.ContentType
                        };
                        using (var reader = new System.IO.BinaryReader(upload.InputStream))
                        {
                            photo.Content = reader.ReadBytes(upload.ContentLength);
                        }
                        product.Files = new List<File> { photo };
                    }
                    db.Products.Add(product);
                    db.SaveChanges();
                    return RedirectToAction("Merchandise");
                }
            }
            catch (RetryLimitExceededException /* dex */)
            {
                //Log the error (uncomment dex variable name and add a line here to write a log.
                ModelState.AddModelError("", "Unable to save changes. Try again.");
            }
            return View(product);
        }

        //GET List Of All Products for sale
        public ActionResult Merchandise()
        {
            ProductOrderViewModel productOrderViewModel = new ProductOrderViewModel();
            productOrderViewModel.Products = db.Products.Include(p => p.Files).ToList();
            return View(productOrderViewModel);
        }

        //Get All Orders that are completed
        public ActionResult ViewAllOrders()
        {
            var orders = db.ProductOrders.Include(p => p.Product).Include(p => p.Order.Participant).Where(p => p.Paid == true).ToList();
            return View(orders);
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


    }
}

FishingProject/Views/Organizations/Create.cshtml
@model FishingProject.Models.Organization

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Organization</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ApplicationId)
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FishingProject/Views/Organizations/CreateLake.cshtml
@model FishingProject.Models.Lake


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <u><h2>Input Lake Information</h2></u>
        <br />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Address.StreetAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address.StreetAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address.StreetAddress, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Address.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address.City, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Address.State, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address.State, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address.State, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Address.ZipCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Address.ZipCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Address.ZipCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FishingProject/Views/Organizations/CreateProduct.cshtml
@model FishingProject.Models.Product

@{
    ViewBag.Title = "CreateProduct";
}

<u><h2>Create Product</h2></u>
<br />
@using (Html.BeginForm("CreateProduct", "Organizations", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Picture", new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="Picture" name="upload" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FishingProject/Views/Organizations/CreateTournament.cshtml
@model FishingProject.Models.Tournament

@{
    ViewBag.Title = "CreateTournament";
}

<u><h2>Create Tournament</h2></u>
<br />
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.OrganizationId)

    <div class="form-group">
        @Html.LabelFor(model => model.TournamentName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TournamentName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TournamentName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.TournamentDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.TournamentDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.TournamentDate, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Lake, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.LakeId, ViewBag.Lakes as SelectList)
        </div>
    </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", "Home")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FishingProject/Views/Organizations/DeleteTeam.cshtml
@model FishingProject.Models.TournamentTeam

@{
    ViewBag.Title = "DeleteTeam";
}

<h2>DeleteTeam</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.TournamentTeamId)
    @Html.HiddenFor(model => model.Tournament.TournamentId)
    @Html.HiddenFor(model => model.Team.TeamId)
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Team.TeamName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Team.TeamName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tournament.TournamentName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tournament.TournamentName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BigBass)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BigBass)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NumberOfFishes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NumberOfFishes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TotalWeight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TotalWeight)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.TournamentTeamId)
        @Html.HiddenFor(model => model.TournamentId)
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-primary btn-xs" /> |
            @Html.ActionLink("Back to Tournament List", "TournamentTable", new { id = Model.TournamentId })
        </div>
    }
</div>

FishingProject/Views/Organizations/EditTournamentTeam.cshtml
@model FishingProject.Models.TournamentTeam

@{
    ViewBag.Title = "EditTournamentTeam";
}

<h2>Edit Team</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Tournament Team</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.TournamentTeamId)
        @Html.HiddenFor(model => model.Tournament.TournamentId)
        @Html.HiddenFor(model => model.Team.TeamId)

        <div class="form-group">
            @Html.LabelFor(model => model.BigBass, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BigBass, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BigBass, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NumberOfFishes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NumberOfFishes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NumberOfFishes, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TotalWeight, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TotalWeight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TotalWeight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Table", "TournamentTable", "Organizations")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FishingProject/Views/Organizations/Index.cshtml
@model IEnumerable<FishingProject.Models.Organization>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.FirstName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastName)
        </td>
    </tr>
}

</table>

FishingProject/Views/Organizations/Merchandise.cshtml
@using FishingProject.Models
@model FishingProject.Models.ProductOrderViewModel

@{
    ViewBag.Title = "Merchandise";
}

<u><h2>Merchandise</h2></u>
<br />

    @foreach (var product in Model.Products)
    {

        using (Html.BeginForm("AddOrder", "Participants", "Post"))
        {
            @Html.AntiForgeryToken()
    <div class="form-horizontal">
    <div class="form-group">
        @if (product.Files.Any(f => f.FileType == FileType.Picture))
        {
            <div class="col-md-10">
                <img src="~/File?id=@product.Files.First(f => f.FileType == FileType.Picture).FileId" alt="picture" style="width:200px;height:200px" />
            </div>
        }
    </div>
    <div class="form-group">
        @Html.LabelFor(modelItem => product.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(modelItem => product.Name)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(modelItem => product.Price, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DisplayFor(modelItem => product.Price)
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(modelItem => product.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(modelItem => product.Quantity, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(modelItem => product.Quantity, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(modelItem => product.Size, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(modelItem => product.Size, new SelectList(Enum.GetValues(typeof(ProductSize))), "Select Size", new { @class = "form-control" })
        </div>
    </div>
    @Html.HiddenFor(itemModel => product.ProductId)
    @Html.HiddenFor(itemModel => product.Name)
    @Html.HiddenFor(itemModel => product.Price)
    @if (this.User.IsInRole("Participant"))
     {
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add To Order" class="btn btn-primary" />
            </div>
        </div>
     }
     else
     {
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("Login", "Account")'">Add To Order</button>
            </div>
        </div>
     }
</div>
    <br />
    <br />
    }
}
@if (User.IsInRole("Participant"))
{
<div>
    <input type="submit" value="View Order" class="btn btn-primary" onclick="location.href='@Url.Action("ViewOrder", "Participants")'" />
</div>
}
<br />
<div>
    @Html.ActionLink("Back to List", "Index", "Home")
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FishingProject/Views/Organizations/TournamentIndex.cshtml
@model IEnumerable<FishingProject.Models.Tournament>

@{ 
    ViewBag.Title = "TournamentIndex";
}
<br />
<br />
<h2 style="text-decoration: underline">List Of Tournaments</h2>
<h5>*Please Log In To Register For Tournament</h5>
<table class="table table-striped table-hover">
    <thead>
        <tr class="bg-primary">
            <th>
                @Html.DisplayNameFor(model => model.TournamentName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TournamentDate)
            </th>
            <th></th>
        </tr>
    </thead>
   @foreach (var item in Model){
        <tr class="active">
        <td>
            @Html.DisplayFor(modelItem => item.TournamentName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.TournamentDate)
        </td>
        <td>
            <button type="button" class="btn-primary btn-xs" onclick="location.href='@Url.Action("AverageBigBassPerTournament", "Home", new { id = item.TournamentId })'">Average Big Bass</button> |
            <button type="button" class="btn-primary btn-xs" onclick="location.href='@Url.Action("AverageTeamWeightPerTeamChart", "Home", new { id = item.TournamentId })'">Average Team Weight</button> |
            <button type="button" class="btn-primary btn-xs" onclick="location.href='@Url.Action("TournamentTeamAmountChart", "Home", new { id = item.TournamentId })'">Teams Per Tournament</button> |
            <button type="button" class="btn-primary btn-xs" onclick="location.href='@Url.Action("TournamentDetails", "Organizations", new { id = item.TournamentId })'">Tournament Details</button> |
            <button type="button" class="btn-primary btn-xs" onclick="location.href='@Url.Action("TournamentTable", "Organizations", new { id = item.TournamentId })'">Teams</button> |
            @if (item.TournamentDate > DateTime.Now)
            {
                if (this.User.IsInRole("Participant"))
                {
                    <button type="button" class="btn-primary btn-xs" onclick="location.href='@Url.Action("RegisterTeam", "Participants", new { id = item.TournamentId })'">Register</button>
                }
                else
                {
                    <button type="button" class="btn-primary btn-xs" onclick="location.href='@Url.Action("Login", "Account")'">Register</button>
                }
            }
            else
            {
                <button type="button" class="btn-primary btn-xs" onclick="location.href='@Url.Action("TournamentTable", "Organizations", new { id = item.TournamentId })'">Results</button>
            }

        </td>
        </tr>
    }
</table>