FishingProject/Models/Participant.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace FishingProject.Models
{
    public class Participant
    {
        [Key]
        public int ParticipantId { get; set; }
        [Display(Name = "First Name")]
        public string FirstName { get; set; }
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [ForeignKey("Team")]
        public int? TeamId { get; set; }
        public Team Team { get; set; }

        [ForeignKey("ApplicationUser")]
        public string ApplicationId { get; set; }
        public ApplicationUser ApplicationUser { get; set; }
    }
}

FishingProject/Controllers/ParticipantsController.cs
using FishingProject.Models;
using Microsoft.AspNet.Identity;
using Stripe;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace FishingProject.Controllers
{
    public class ParticipantsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Participants
        public ActionResult Index()
        {
            var participantId = User.Identity.GetUserId();
            var participant = db.Participants.Where(p => p.ApplicationId == participantId).ToList();
            return View(participant);
        }

        // GET: Participants/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Participants/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ParticipantId,FirstName,LastName,TeamId,ApplicationId")] Participant participant)
        {

            if (ModelState.IsValid)
            {
                participant.ApplicationId = User.Identity.GetUserId();
                db.Participants.Add(participant);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(participant);
        }

        // GET: Participants/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Participant participant = db.Participants.Find(id);
            if (participant == null)
            {
                return HttpNotFound();
            }
            return View(participant);
        }

        // GET: Participants/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Participant participant = db.Participants.Find(id);
            if (participant == null)
            {
                return HttpNotFound();
            }
            return View(participant);
        }

        // POST: Participants/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ParticipantId,FirstName,LastName,TeamId,ApplicationId")] Participant participant)
        {
            if (ModelState.IsValid)
            {
                db.Entry(participant).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(participant);
        }

        // GET: Participants/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Participant participant = db.Participants.Find(id);
            if (participant == null)
            {
                return HttpNotFound();
            }
            return View(participant);
        }

        // POST: Participants/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Participant participant = db.Participants.Find(id);
            db.Participants.Remove(participant);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        //GET: Participants/CreateTeam when registering for a certain tournament
        public ActionResult RegisterTeam(int id)
        {
            TournamentTeamViewModels tournamentTeamView = new TournamentTeamViewModels();
            var tournament = db.Tournaments.FirstOrDefault(t => t.TournamentId == id);
            tournamentTeamView.Tournament = tournament;
            return View(tournamentTeamView);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RegisterTeam(TournamentTeamViewModels teamViewModels)
        {
                var currentUserId = User.Identity.GetUserId();
                Participant participant = db.Participants.Where(p => p.ApplicationId == currentUserId).Single();
                if(participant.TeamId == null)
                {
                    participant.TeamId = teamViewModels.Team.TeamId;
                }
                else
                {
                teamViewModels.Team.TeamId = participant.TeamId.Value;
                }
                db.Teams.Add(teamViewModels.Team);
                db.SaveChanges();

                TournamentTeam tournamentTeam = new TournamentTeam();
                tournamentTeam.TeamId = teamViewModels.Team.TeamId;
                tournamentTeam.TournamentId = teamViewModels.Tournament.TournamentId;
                db.TournamentTeams.Add(tournamentTeam);
                db.SaveChanges();
                return RedirectToAction("TournamentIndex", "Organizations");
        }

        [HttpPost]
        public ActionResult Charge(string stripeEmail, string stripeToken)
        {
            var currentCustomer = User.Identity.GetUserId();
            var user = db.Participants.Where(p => p.ApplicationId == currentCustomer).Single();
            var order = db.ProductOrders.Include(p => p.Product).Where(p => p.Order.ParticipantId == user.ParticipantId).ToList();
            decimal total = 0;
            foreach (var product in order)
            {
                total += product.Total;
            }

            var customers = new CustomerService();
            var charges = new ChargeService();
            StripeConfiguration.ApiKey = Keys.SecretKey;
            var customer = customers.Create(new CustomerCreateOptions
            {
                Email = stripeEmail,
                Source = stripeToken
            });

            var currentUserId = User.Identity.GetUserId().ToString();
            var participant = db.Participants.FirstOrDefault(p => p.ApplicationId == currentUserId);
            var charge = charges.Create(new ChargeCreateOptions
            {
                Amount = Convert.ToInt64(total * 100),
                Description = "Sample Charge",
                Currency = "usd",
                CustomerId = customer.Id
            });

            var completeOrder = db.Orders.Where(o => o.ParticipantId == user.ParticipantId && o.PendingOrder == true).Single();
            completeOrder.PendingOrder = false;
            db.SaveChanges();
            foreach (var product in order)
            {
                product.Paid = true;
                db.SaveChanges();
            }
            return RedirectToAction("Index", "Home");
        }

        public ActionResult StripeIndex()
        {
            var stripePublishKey = Keys.PublishableKey;
            ViewBag.StripePublishKey = stripePublishKey;
            return View();
        }

        //ADD Order If Order Is Not Pending/Else ADD Product To Existing Order
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddOrder(Models.Product product)
        {
            var newCustomer = User.Identity.GetUserId();
            Participant participant = db.Participants.Where(p => p.ApplicationId == newCustomer).Single();
            Models.Order order = db.Orders.Where(o => o.ParticipantId == participant.ParticipantId && o.PendingOrder == true).FirstOrDefault();
            if (order == null)
            {
                var newOrder = new Models.Order();
                newOrder.ParticipantId = participant.ParticipantId;
                newOrder.PendingOrder = true;
                db.Orders.Add(newOrder);
                db.SaveChanges();

                ProductOrder productOrder = new ProductOrder();
                productOrder.OrderId = newOrder.OrderId;
                productOrder.ProductId = product.ProductId;
                productOrder.Quantity = product.Quantity;
                productOrder.Size = product.Size;
                productOrder.Total = product.Quantity * product.Price;
                db.ProductOrders.Add(productOrder);
                db.SaveChanges();
            }
            else
            {
                ProductOrder productOrder = new ProductOrder();
                productOrder.OrderId = order.OrderId;
                productOrder.ProductId = product.ProductId;
                productOrder.Quantity = product.Quantity;
                productOrder.Size = product.Size;
                productOrder.Total = product.Quantity * product.Price;
                db.ProductOrders.Add(productOrder);
                db.SaveChanges();
            }
            return RedirectToAction("ViewOrder");
        }
        //GET Order That Contains All Products For That Order
        public ActionResult ViewOrder()
        {
            var currentCustomer = User.Identity.GetUserId();
            var customer = db.Participants.Where(p => p.ApplicationId == currentCustomer).Single();
            var order = db.ProductOrders.Include(p => p.Product).Where(p => p.Order.ParticipantId == customer.ParticipantId && p.Paid == false).ToList();
            decimal total = 0;
            foreach (var product in order)
            {
                total += product.Total;
            }
            ViewBag.Total = total;
            return View(order);
        }

        //Get Product id
        public ActionResult EditOrder(int? id)
        {
            if (id == null)

FishingProject/Views/Participants/Create.cshtml
@model FishingProject.Models.Participant

@{ 
    ViewBag.Title = "Create";
}

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Participant</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FishingProject/Views/Participants/DeleteProduct.cshtml
@model FishingProject.Models.ProductOrder

@{
    ViewBag.Title = "DeleteProduct";
}

<h3>Are you sure you want to delete this product?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Product.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Product.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Size)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Size)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Quantity)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Total)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Total)
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.ProductOrderId)

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-primary btn-xs" /> |
            @Html.ActionLink("Back to Order", "ViewOrder")
        </div>
    }
</div>

FishingProject/Views/Participants/EditOrder.cshtml
@using FishingProject.Models
@model FishingProject.Models.ProductOrder

@{
    ViewBag.Title = "EditOrder";
}

@using (Html.BeginForm("EditOrder", "Participants", "Post"))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <br />
       <u><h2>Edit Order</h2></u>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ProductOrderId)
        @Html.HiddenFor(model => model.ProductId)
        @Html.HiddenFor(model => model.OrderId)
        @Html.HiddenFor(model => model.Paid)
        @Html.HiddenFor(model => model.Total)

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Product.Size, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.Product.Size, new SelectList(Enum.GetValues(typeof(ProductSize))), "Select Size", new { @class = "form-control" })
            </div>
        </div>
        @Html.HiddenFor(model => model.ProductId)
        @Html.HiddenFor(model => model.OrderId)
        @Html.HiddenFor(model => model.Paid)
        @Html.HiddenFor(model => model.Total)

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Order", "ViewOrder", "Participants")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FishingProject/Views/Participants/Index.cshtml
@model IEnumerable<FishingProject.Models.Participant>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.FirstName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastName)
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
        </tr>
    }

</table>

FishingProject/Views/Participants/RegisterTeam.cshtml
@model FishingProject.Models.TournamentTeamViewModels

@{ 
    ViewBag.Title = "RegisterTeam";
}
<br />
<br />
<h3 style="text-decoration: underline">Please Register Team Here</h3>
<h5>*Remember To Read The Tournament Rules Before Registering</h5>
<br />
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.HiddenFor(model => model.Tournament.TournamentId)
        @Html.LabelFor(model => model.Team.TeamName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Team.TeamName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Team.TeamName, "", new { @class = "text-danger" })
        </div>
    </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Register" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "TournamentIndex", "Organizations")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FishingProject/Views/Participants/ViewOrder.cshtml
@model IEnumerable<FishingProject.Models.ProductOrder>
@using System.Globalization

<u><h2>Your Order</h2></u>
<br />
@using (Html.BeginForm())
{
    <table class="table table-striped table-hover">
        <thead>
            <tr class="bg-primary">
                <th>
                    @Html.DisplayNameFor(model => model.OrderId)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Product.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Product.Size)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Product.Quantity)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Total)
                </th>
                <th></th>
            </tr>
        </thead>
        @foreach (var item in Model)
        {
            <tr class="active">
                <td>
                    @Html.DisplayFor(modelItem => item.OrderId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Product.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Size)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Total)
                </td>
                <td>
                    @Html.ActionLink("Edit Order", "EditOrder", new { id = item.ProductOrderId }) |
                    @Html.ActionLink("Delete", "DeleteProduct", new { id = item.ProductOrderId })
                </td>
            </tr>
        }
    </table>
}
<div>
    <h5>Order Total</h5>
    <form action="/Participants/Charge" method="POST">
        <article>
            <label>Amount: @ViewBag.Total</label>
        </article>
        <script src="//checkout.stripe.com/v2/checkout.js"
                class="stripe-button"
                data-key="@Keys.PublishableKey"
                data-locale="auto"
                data-description="Sample Charge"
                data-amount="">
        </script>
    </form>
</div>
<br />
<div>
    @Html.ActionLink("Continue Order", "Merchandise", "Organizations")
</div>